# Generated by Django 6.0.4 on 2026-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
