# Generated by Django 6.0.4 on 2026-05-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poi_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
